#!/bin/bash

BVERSION=$1

echo "Building Framework on [$BVERSION]"

if [ "$BVERSION"  == "release" ];
then
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -O3 -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/core/Core.cpp -o obj/Release/src/core/Core.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -O3 -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/core/LinuxFramework.cpp -o obj/Release/src/core/LinuxFramework.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -O3 -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/scene/Cube.cpp -o obj/Release/src/scene/Cube.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -O3 -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/scene/GLMesh.cpp -o obj/Release/src/scene/GLMesh.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -O3 -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/scene/GLQuad.cpp -o obj/Release/src/scene/GLQuad.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -O3 -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/scene/PrimitiveInstance.cpp -o obj/Release/src/scene/PrimitiveInstance.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -O3 -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/scene/PrimitiveManager.cpp -o obj/Release/src/scene/PrimitiveManager.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -O3 -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/scene/SceneProp.cpp -o obj/Release/src/scene/SceneProp.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -O3 -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/scene/Triangle.cpp -o obj/Release/src/scene/Triangle.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -O3 -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/utils/Camera.cpp -o obj/Release/src/utils/Camera.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -O3 -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/utils/InputManager.cpp -o obj/Release/src/utils/InputManager.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -O3 -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/utils/Timer.cpp -o obj/Release/src/utils/Timer.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -O3 -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/utils/Utils.cpp -o obj/Release/src/utils/Utils.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -O3 -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/utils/XDataBase.cpp -o obj/Release/src/utils/XDataBase.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -O3 -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/utils/XMaths.cpp -o obj/Release/src/utils/XMaths.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -O3 -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/video/BaseDriver.cpp -o obj/Release/src/video/BaseDriver.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -O3 -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/video/GLDriver.cpp -o obj/Release/src/video/GLDriver.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -O3 -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/video/GLRT.cpp -o obj/Release/src/video/GLRT.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -O3 -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/video/GLShader.cpp -o obj/Release/src/video/GLShader.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -O3 -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/video/GLTexture.cpp -o obj/Release/src/video/GLTexture.o
rm -f bin/Release/libFramework.a
ar -r -s bin/Release/libFramework.a obj/Release/src/core/Core.o obj/Release/src/core/LinuxFramework.o obj/Release/src/scene/Cube.o obj/Release/src/scene/GLMesh.o obj/Release/src/scene/GLQuad.o obj/Release/src/scene/PrimitiveInstance.o obj/Release/src/scene/PrimitiveManager.o obj/Release/src/scene/SceneProp.o obj/Release/src/scene/Triangle.o obj/Release/src/utils/Camera.o obj/Release/src/utils/InputManager.o obj/Release/src/utils/Timer.o obj/Release/src/utils/Utils.o obj/Release/src/utils/XDataBase.o obj/Release/src/utils/XMaths.o obj/Release/src/video/BaseDriver.o obj/Release/src/video/GLDriver.o obj/Release/src/video/GLRT.o obj/Release/src/video/GLShader.o obj/Release/src/video/GLTexture.o
fi


if [ "$BVERSION" == "debug" ];
then
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -g -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/core/Core.cpp -o obj/Debug/src/core/Core.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -g -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/core/LinuxFramework.cpp -o obj/Debug/src/core/LinuxFramework.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -g -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/scene/Cube.cpp -o obj/Debug/src/scene/Cube.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -g -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/scene/GLMesh.cpp -o obj/Debug/src/scene/GLMesh.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -g -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/scene/GLQuad.cpp -o obj/Debug/src/scene/GLQuad.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -g -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/scene/PrimitiveInstance.cpp -o obj/Debug/src/scene/PrimitiveInstance.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -g -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/scene/PrimitiveManager.cpp -o obj/Debug/src/scene/PrimitiveManager.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -g -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/scene/SceneProp.cpp -o obj/Debug/src/scene/SceneProp.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -g -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/scene/Triangle.cpp -o obj/Debug/src/scene/Triangle.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -g -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/utils/Camera.cpp -o obj/Debug/src/utils/Camera.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -g -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/utils/InputManager.cpp -o obj/Debug/src/utils/InputManager.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -g -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/utils/Timer.cpp -o obj/Debug/src/utils/Timer.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -g -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/utils/Utils.cpp -o obj/Debug/src/utils/Utils.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -g -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/utils/XDataBase.cpp -o obj/Debug/src/utils/XDataBase.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -g -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/utils/XMaths.cpp -o obj/Debug/src/utils/XMaths.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -g -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/video/BaseDriver.cpp -o obj/Debug/src/video/BaseDriver.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -g -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/video/GLDriver.cpp -o obj/Debug/src/video/GLDriver.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -g -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/video/GLRT.cpp -o obj/Debug/src/video/GLRT.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -g -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/video/GLShader.cpp -o obj/Debug/src/video/GLShader.o
g++ -std=c++11 -Wall -DOS_LINUX -DFREEGLUT_GLES -DFREEGLUT_WAYLAND -g -Iinclude -I../Framework -I../Librerias/stb/include -I../Librerias/freeglut-linux/include -I../Librerias/glew-2.0.0/include -c /home/Camus/Dev/T800-Cloned/T800-Project/T800/Framework/src/video/GLTexture.cpp -o obj/Debug/src/video/GLTexture.o
rm -f bin/Debug/libFramework.a
ar -r -s bin/Debug/libFramework.a obj/Debug/src/core/Core.o obj/Debug/src/core/LinuxFramework.o obj/Debug/src/scene/Cube.o obj/Debug/src/scene/GLMesh.o obj/Debug/src/scene/GLQuad.o obj/Debug/src/scene/PrimitiveInstance.o obj/Debug/src/scene/PrimitiveManager.o obj/Debug/src/scene/SceneProp.o obj/Debug/src/scene/Triangle.o obj/Debug/src/utils/Camera.o obj/Debug/src/utils/InputManager.o obj/Debug/src/utils/Timer.o obj/Debug/src/utils/Utils.o obj/Debug/src/utils/XDataBase.o obj/Debug/src/utils/XMaths.o obj/Debug/src/video/BaseDriver.o obj/Debug/src/video/GLDriver.o obj/Debug/src/video/GLRT.o obj/Debug/src/video/GLShader.o obj/Debug/src/video/GLTexture.o
fi

if [ "$BVERSION" == "" ];
then
echo "Sorry? I don't get what kind of release you want.. choose release or debug then."
fi

